import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os


subject = "Sanity Results for UNHIOL Test"
email_body = "This is an autogenerated email."
sender_email_id = "jatin.singhal@wdc.com"
email = "jatin.singhal@wdc.com"
smtp_server = "mailrelay.wdc.com"
report_file_path = "C:/Users/39231/Desktop/dm_results"

msg = MIMEMultipart()
msg.preamble = subject
msg.add_header("From", "".join(sender_email_id))
msg.add_header("Subject", subject)
msg.add_header("To", email)
msg.attach(MIMEText(email_body))

'''
for each_file in os.listdir(report_file_path):
	resultFile = os.path.join(report_file_path,each_file)
	part = MIMEBase('application', "octet-stream")
	part.set_payload(open(resultFile, "rb").read())
	encoders.encode_base64(part)
	part.add_header('Content-Disposition', 'attachment; filename="%s"' % os.path.basename(resultFile))
	msg.attach(part)
'''

server = smtplib.SMTP(smtp_server)
server.sendmail(sender_email_id, email, msg.as_string())